sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t reactapp .

script:
  - docker run -e CI=true reactapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2" 
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-406474718927"
  bucket_path: "docker-react-app"
  on: 
    branch: master
    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

after_success:
  - echo "Deploy success"